#!/usr/bin/env bash
# Installs and configures Nginx web server

# Update package list and install nginx
apt-get update -y
apt-get install nginx -y

# Create a simple HTML page with the required text
echo "Holberton School for the win!" > /var/www/html/index.html

# Ensure Nginx is configured to listen on port 80 (default)
# Start Nginx service
service nginx start
