#!/usr/bin/env bash
# Script that installs and configures Nginx web server

# Update package list
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create the HTML page with "Holberton School"
echo "Holberton School" > /var/www/html/index.html

# Make sure Nginx default config is set correctly
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    
    server_name _;
    
    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart nginx using service command (not systemctl)
service nginx restart
