#!/usr/bin/env bash
# Configures Nginx with a custom 404 page

# Update and install nginx
apt-get update -y
apt-get install nginx -y

# Create the index page
echo "Holberton School for the win!" > /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure redirect
sed -i '/server_name _;/a \\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Configure custom 404 page
sed -i '/server_name _;/a \\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Start nginx
service nginx start
